### PR TITLE
Update gherkin to 4.0.0 version

### PR DESCRIPTION
**Pull request by ikozakov**
Created to fix this issue: https://github.com/smoll/greener/issues/34

### CODE REVIEW

**Comment by smoll** [comment]
Thanks for this @ikozakov. I haven't looked at this project in years, but if you're using it I'm happy.

Let me know if you're interested in taking over as owner.

**Comment by ikozakov** [comment]
hey @smoll thanks for looking into it.
you've done lots of work there, so you must be the owner :)
I can help to fix something if needed.
could you release a new version (0.2.0) of `greener`?

**Comment by smoll** [comment]
@ikozakov 0.2.0 released

**Comment by ikozakov** [comment]
Thank you very much 👍

**Pull request merged**
